### ISSUE TITLE
Uploading records with dataset.from_geo_features(geodataframe) fails on geometry field that is 'null'

### ISSUE THREAD

**Issue by mdonovan-tamr** [Datatamer/unify-client-python#148]
# 🐛 bug report

I was using the python client to upload a dataset, an it failed using `dataset.from_geo_features(geodataframe)` on records that had null for the geometry field.
I removed the records that had null geometry field and then the dataset uploaded successfully

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client |
| Tamr Unify server |
| Python            |
| Operating System  |

**Comment by mdonovan-tamr** [comment]
Example record:
{ "type": "Feature", "properties": { "icn": "201701395957", "crash_id": "9322007", "county_code": "16", "crash_yr": "17", "crash_month": "3", "crash_day": "2", "number_of_vehicles": "1", "day_of_week_code": "4", "crash_hour": "18", "city_code": "1051", "city_class_code": "3", "township": "", "collision_type_code": "1", "total_fatals": "0", "total_injured": "1", "no_injuries": "1", "a_injuries": "0", "b_injuries": "1", "c_injuries": "0", "crash_severity": "Injury", "agency_code": "1", "route_number": "", "milestation": "0.00", "class_of_trafficway_code": "8", "nhs": "N", "traffic_control_device_code": "3", "road_surface_condition_code": "1", "road_defects_code": "1", "light_condition_code": "5", "weather_code": "1", "cause1_code": "18", "cause2_code": "99", "railroad_crossing_number": "(N\/A)", "time_of_crash": "06:40 PM", "traffic_control_device_condition_code": "4", "intersection_related": "Y", "hit_and_run": "Y", "crash_date": "3\/2\/2017", "number_of_lanes": "(UNK)", "alignment_code": "2", "trafficway_description_code": "1", "roadway_functional_class_code": "70", "work_zone_related": "N", "city_township_flag": "C", "ts_crash_coordinate_x": "2971472.58563958", "ts_crash_coordinate_y": "1866434.00494107", "crash_report_county": "Cook", "day_of_week": "Thursday", "type_of_first_crash": "Pedestrian", "city_name": "Chicago", "city_class": "Chicago", "class_of_trafficway": "City Streets Urban", "cause1": "Unable to Determine", "cause2": "(N\/A)", "traffic_control_device": "Traffic Signal", "traffic_control_device_cond": "Functioning Properly", "road_surface_cond": "Dry", "road_defects": "No Defects", "crash_injury_severity": "B Injury Crash", "lighting_cond": "Darkness \/ Lighted Road", "weather_cond": "Clear", "road_alignment": "Straight On Grade", "trafficway_descrip": "Not Divided", "roadway_functional_class": "Minor Arterial (Urban)", "investigating_agency_descrip": "City", "crash_severity_cd": "2", "damaged_property1": "", "damaged_property2": "", "agency_report_year": "17", "agency_report_number": "JA172855", "sfe": "C130331486", "did_crash_occur_in_work_zone": "N", "work_zone_type": "(N\/A)", "were_workers_present": "N", "work_zone": "(N\/A)" }, "geometry": null }

**Comment by mdonovan-tamr** [comment]
Error:

Traceback (most recent call last):
  File "./geo.py", line 26, in <module>
    dataset.from_geo_features(geodataframe)
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/models/dataset/resource.py", line 177, in from_geo_features
    self._features_to_updates(features, record_id, key_attrs, self._geo_attr)
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/models/dataset/resource.py", line 92, in update_records
    data=_stringify_updates(records),
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/client.py", line 124, in post
    return self.request("POST", endpoint, **kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/client.py", line 107, in request
    response = self.session.request(method, url, auth=self.auth, **kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 469, in send
    for i in request.body:
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/models/dataset/resource.py", line 85, in _stringify_updates
    for update in updates:
  File "/Applications/anaconda3/lib/python3.7/site-packages/tamr_unify_client/models/dataset/resource.py", line 321, in _features_to_updates
    id_attr: feature["id"],
TypeError: string indices must be integers

**Comment by CaspianA1** [comment]
Record in question has no ID.
