### ISSUE TITLE
Attribute's collection.py should not require JSON on creation

### ISSUE THREAD

**Issue by charlottemoremen** [Datatamer/unify-client-python#176]
# 🐛 bug report

Collection.py has a data param in __init__ and shouldn't, should only fetch data when streaming begins, from_json method shouldn't exist because of this

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client |
| Tamr Unify server |
| Python            |
| Operating System  |

**Comment by juliamcclellan** [comment]
Clone of #175
