### ISSUE TITLE
If nan is in record then it is uploaded to tamr as the string "nan" rather than a missing field

### ISSUE THREAD

**Issue by Lordluen** [Datatamer/unify-client-python#194]
# 🙋 feature request
Currently, any NaN values cause Unify to throw a 400 error. I believe you should be given the option to ignore NaNs.

## 🤔 Expected Behavior
There should be a way to filter out NaN values so as not to fail when uploading NaN values.

## 😯 Current Behavior
There is no alternative to this other than changing all of your `NaN`'s to `None` before getting to the `update_records` function.

## 💁 Possible Solution
Replace the current replace the current tamr_unify_client/models/dataset/resource.py:75 with
```
   def update_records(self, records, ignore_nan=False):
        """Send a batch of record creations/updates/deletions to this dataset.

        :param records: Each record should be formatted as specified in the `Public Docs for Dataset updates <https://docs.tamr.com/reference#modify-a-datasets-records>`_.
        :type records: iterable[dict]
        :returns: JSON response body from server.
        :rtype: :py:class:`dict`
        """

        def _stringify_updates(updates, ignore_nan):
            for update in updates:
                yield simplejson.dumps(update, ignore_nan=ignore_nan).encode("utf-8")

        return (
            self.client.post(
                self.api_path + ":updateRecords",
                headers={"Content-Encoding": "utf-8"},
                data=_stringify_updates(records, ignore_nan),
            )
            .successful()
            .json()
        )
```

This requires adding the `simplejson` package, but it is a convenient solution since it already exists and solves this exact problem.

## 🔦 Context
I would have needed to manually go through the data and convert all NaN's to something else in the json string, though this causes the possibility of removing the string "NaN" which might actually be valid.

Solving this in our code for uploading to Unify prevents this problem and is pretty lightweight.

## 💻 Examples
See above description for examples.

**Comment by juliamcclellan** [comment]
@Lordluen I'm trying to test this out, and I'm finding that in the current version if `NaN` is in the update, the update request fails with a 400 error because `json.dumps` is preserving `NaN` as `NaN` rather than converting it to `"nan"`. Not sure if I'm doing something differently than you did, could you give an example of how you called the function?

**Comment by Lordluen** [comment]
@juliamcclellan I actually found this was an issue with the versioned API endpoint for updating records to a dataset. At the time I was using the requests library, and json.dumps. I have not actually tested this failing in the python client, but I know it uses the same methods. Let me see if I can get you the data and the script I used to see if we can reproduce this.

**Comment by Lordluen** [comment]
This is the script: https://github.com/Datatamer/customers-staples/blob/master/scripts/bulk_load/upload_scale_records.py#L66

**Comment by Lordluen** [comment]
The data can be found on GCP here: [GCS](https://console.cloud.google.com/storage/browser/tamr-fe) in the `staples/semi-clean-all-data`.

**Comment by Lordluen** [comment]
After talking with @juliamcclellan my original report was inaccurate. In reality, Unify just throws a 400 error when confronted with a NaN in the json. So slightly different issue, still requiring the same solution.

**Comment by Lordluen** [comment]
I updated the original comment appropriately.
