### ISSUE TITLE
Documentation for the Python Client

### ISSUE THREAD

**Issue by JuliaMalkin** [Datatamer/unify-client-python#200]
# 🙋 feature request
Documentation for the Python client: intro, references, examples
## 🤔 Expected Behavior
Python client needs to be documented, and this documentation needs to be automated, and included a a link from the readme.io page, together with other docs.
## 😯 Current Behavior
unknown to me
## 💁 Possible Solution
Meet with Julia and talk this through please :)
## 🔦 Context
We have swagger doc that is separate from public docs. I need to understand where python client is in this picture, and how to make it part of our docs.
## 💻 Examples
https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/python/example_code/s3
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/examples.html

**Comment by juliamcclellan** [comment]
There's a link to the client documentation in readme.io: https://docs.tamr.com/docs/tamr-unify-python-client

**Comment by pcattori** [comment]
@JuliaMalkin and I caught up offline. I walked her through the [Python Client docs](https://tamr-unify-python-client.readthedocs.io/en/stable/) and we discussed different approaches towards centralizing/linking to all Tamr docs.
