### ISSUE TITLE
be able to get schema mapping recipe_id and dedup recipe_id

### ISSUE THREAD

**Issue by YJ-tamr** [Datatamer/unify-client-python#216]
# 🙋 feature request

when using internal API, these 2 recipe_id are frequently need to call endpoint in schema mapping and mastering workflow. will be convenient if both schema mapping recipe_id and dedup recipe_id can be fetched by python client 

## 💁 Possible Solution

```python
def get_project_recipe_id(unify, project_tgr):
        project_relativeId = project_util.get_project_metadata(unify, project_tgr)["relativeId"]
        abs_path_API = "/api/recipe/"
        resp = unify.get(
            '{}{}'.format(abs_path_API, project_relativeId),
            headers={
                'Content-Type': 'application/json',
                'Content-Encoding': 'utf-8' }).json()
        smr_recipe_id = resp['data']['steps'][1]['id']
        return smr_recipe_id
```

**Comment by pcattori** [comment]
@yizhiyintamr recipes are an internal API concept not exposed by the versioned Unify API. Since the Python Client makes backwards compatibility guarantees, it cannot depend on internal APIs or concepts from the internal APIs.

**Comment by YJ-tamr** [comment]
thank you for your explaination. I think you confused me with Yizhi by the
way.

Yi Jin

Sales Engineer

Tamr lnc.

66 Church street

Cambridge, MA 02138

**Comment by pcattori** [comment]
@YJ-tamr oops, yea I typed "@yi" and hit enter without looking 😛 sorry!
