### ISSUE TITLE
Python version (and any other requirements) should be specified more visibly

### ISSUE THREAD

**Issue by nsylv** [Datatamer/unify-client-python#33]
Got the following error after running the quickstart example in the docs:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from tamr_unify_client import Client
  File "/home/nikki/.local/lib/python2.7/site-packages/tamr_unify_client/__init__.py", line 1, in <module>
    from tamr_unify_client.client import Client
  File "/home/nikki/.local/lib/python2.7/site-packages/tamr_unify_client/client.py", line 69
    return f"{method} {url} : {response.status_code}"
                                                    ^
SyntaxError: invalid syntax
```

The issue is that I'm running python 2.7, but 3.6+ is required.  Maybe we could add a requirements section to the docs and github to help make this more visible?

**Comment by pcattori** [comment]
Currently, the Python version is specified in 3 places:

1) [README](https://github.com/Datatamer/unify-client-python/blob/master/README.md) badge
2) [PyPI page](https://pypi.org/project/tamr-unify-client/) in the `Classifiers` section
3) [.travis.yml](https://github.com/Datatamer/unify-client-python/blob/master/.travis.yml) / [Travis CI tests](https://travis-ci.org/Datatamer/unify-client-python)

---

We could add a "Requirements" section to the [installation instructions](https://tamr-unify-python-client.readthedocs.io/en/stable/user-guide/installation.html) specifying the compatible Python versions to make it more visible.

**Comment by pcattori** [comment]
#58 adds a Python compatibility message at the top of the installation docs.

#40 prevents `pip install tamr-unify-client` from installing `tamr-unify-client` on incompatible Python versions. NOTE: this only affects version 0.3.0 and newer. E.g. trying to `pip install tamr-unify-client` from Python2.7 will result in `tamr-unify-client` version 0.2.0 being installed.
