### ISSUE TITLE
HTTP/HTTPS for username/password authentication

### ISSUE THREAD

**Issue by YJ-tamr** [Datatamer/unify-client-python#39]
whether the username password is send through http, or secure (authenticated and encrypted) connections, like HTTPS?

**Comment by pcattori** [comment]
By default, the Python Client [assumes you would like to use the `http` protocol](https://github.com/Datatamer/unify-client-python/blob/master/tamr_unify_client/client.py#L52). You can configure this via the `protocol` parameter to the client:

```python
from tamr_unify_client import Client

unify = Client(..., protocol='https', ...)
```

Of course, this just sets HTTPS as the protocol for the Python Client. You'll have to ensure your instance of Unify is configured to use HTTPS as well for this to work.
