### ISSUE TITLE
v0.3.0 client doesn't properly override base_path if specified

### ISSUE THREAD

**Issue by along528** [Datatamer/unify-client-python#54]
I tried setting the `base_path='api'` to use the requests method for non-versioned apis, but it seems to not be picking it up. See below:
```
Python 3.7.0 (default, Nov 10 2018, 18:44:49) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tamr_unify_client import Client
>>> from tamr_unify_client.auth import UsernamePasswordAuth
>>> catmando_host = 'localhost'
>>> catmando_port = 9030
>>> tamr_user = 'admin'
>>> tamr_pw = 'dt'
>>> auth=UsernamePasswordAuth(tamr_user, tamr_pw)
>>> catmando_client = Client(auth, host=catmando_host, port=catmando_port, base_path='api')
>>> response = catmando_client.request( 'GET', 'service/health', headers={'Accept': 'application/json'})
>>> response
<Response [404]>
>>> response.url
'http://localhost:9030/service/health'
```

More investigation reveals that it is a problem with `urllib.parse.urljoin`:
```Python 3.7.0 (default, Nov 10 2018, 18:44:49) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urljoin
>>> urljoin('http://localhost:9030'+'/'+'api','service/health')
'http://localhost:9030/service/health'```

**Comment by pcattori** [comment]
Quick answer: As of 0.3.0, base paths need a trailing `/`.

The use of `urljoin` is to allow easier calling of internal API endpoints. New docs for how to call internal API endpoints (#30) should make this explicit. Plus we may want to add this to the [0.3.0 changelog entry](https://github.com/Datatamer/unify-client-python/blob/master/CHANGELOG.md#030) since its technically a breaking change (though an easily fixed one).

**Comment by pcattori** [comment]
Proposed Acceptance Criteria:

- In the [0.3.0 changelog](https://github.com/Datatamer/unify-client-python/blob/master/CHANGELOG.md#030), include a message about the trailing `/` requirement for `base_path` and call it out as a breaking change.
- Update the docs (as described in #30) to be consistent with the new trailing `/` requirement.
  - Includes fixing any docstrings that reference the `base_path` (e.g. [`Client` docstring](https://github.com/Datatamer/unify-client-python/blob/master/tamr_unify_client/client.py#L38))

**Comment by along528** [comment]
Can we also have a warning if someone does not include the trailing `/` that the base_path will not be used? Or even an error? Is there a reason we would want to allow someone to specify the base_path without the trailing `/`?

**Comment by pcattori** [comment]
@along528 I updated the AC to include automatically filling in the trailing `/` for `base_path` when it is missing.
