### ISSUE TITLE
Change `data` to `_data`

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/unify-client-python#61]
# 💬 RFC

Many classes within tamr_unify_client use a `data` field member for the static information, often loaded from a server's JSON response upon fetching the object.

This object is not documented. Because of its direct relationship to the server response, it's also subject to change from version to version. It should be messaged as a private by the underscore naming convention (`_data`)

This also affects tab completion in the python3 interactive repl.

## 🔦 Context

This is particularly misleading when working with a dataset object, because it looks like it ought to be the collection of the dataset's records.

```python3
>>> dataset = project.unified_dataset()
>>> dataset.
dataset.api_path         dataset.data             dataset.external_id      dataset.from_json(       dataset.records(         dataset.relative_id      dataset.status(          dataset.update_records(
dataset.client           dataset.description      dataset.from_data(       dataset.name             dataset.refresh(         dataset.resource_id      dataset.tags             dataset.version
>>> dataset.
```

## 💻 Examples

- Change base_resource to use `_data`
- Change various `self.data` references to `self._data`

**Comment by pcattori** [comment]
Go for launch! 🚀
