### ISSUE TITLE
Improve documentation on Dataset.update_records recordId

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/unify-client-python#68]
# 🙋 feature request

I discovered, through experimentation, that `Dataset.update_records` uses the datasets `keyAttributeNames` as the `recordId`. The corresponding value in the `record` itself is ignored.

I don't know how this works if there are multiple key attributes.

This was not clear through documentation. The python client documentation defers to https://docs.tamr.com/reference#modify-a-datasets-records which says only:

Field|Description
-------|------
action|The action being requested.CREATE or DELETE.
recordId|**The ID of the record.**
record|Optional. The information the new record will contain upon creation. Fields in the record must exist in the schema of the dataset they are being added to. If fields are not in the schema, they will be ignored.

This isn't sufficient information to understand how to use the API without experimentation and close scrutiny.

**Comment by juliamcclellan** [comment]
Since `update_records` was deprecated with `upsert_records` and `delete_records` in #214, this is no longer relevant.
