### ISSUE TITLE
Add clusters() method to mastering project

### ISSUE THREAD

**Issue by olivito** [Datatamer/unify-client-python#71]
Could you add a method .clusters() to the MasteringProject object?  It should in turn support a .refresh() method to recreate the clusters without publishing them.  This functionality is currently missing in the python client but is necessary for a continuous mastering workflow.

In the docs, the Continuous Mastering example should also be updated to include this step (before publishing clusters).

**Comment by pcattori** [comment]
Labeling this as a bug since its part of the "Continuous Mastering" workflow that we should support. (As opposed to a feature request).
