### ISSUE TITLE
Add useful repr to various object throughout the codebase

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/unify-client-python#78]
# 🙋 feature request

Desire: Add a useful repr() to all common objects throughout unify-client-python.

## 🤔 Expected Behavior

interactive python and `repr(x)` for objects from the library should show some elements that are useful for a developer, though they need not be eval-compatible.

## 😯 Current Behavior

Default Python `Object.__repr__`

## 💁 Possible Solution

Discussed and negotiated in PR #59

**Comment by DerrickRice** [comment]
Landing changes in PR #59 for Client, then proposing a bigger PR for other objects.

Later PR will result in a broader scope for the Changelog.

**Comment by pcattori** [comment]
Implemented in #59 and #83
